name: Scheduled Empty Commit
permissions:
  contents: write

on:
  schedule:
    # run every 10 hours (under the ~12h sleep window)
    - cron: '0 */10 * * *'

jobs:
  keep_awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: main   

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit and push
        run: |
          git commit --allow-empty -m "[keepalive] $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin HEAD:main
